stages:
  - verify

test:
  stage: verify
  image: golang:1.17-alpine
  except:
    refs:
      - tags
  before_script:
    - apk update && apk add git build-base
    - export GOPRIVATE=gitlab.com
    - git config --global url."https://$GITLAB_USER:$GITLAB_ACCESS_TOKEN@gitlab.com/".insteadOf "https://gitlab.com/"
  script:
    - go test ./...
