stages:
    - verify

test:
    stage: verify
    image: golang:1.19-alpine
    except:
        refs:
            - tags
    before_script:
        - apk update && apk add git build-base
    script:
        - go test ./...
